//! Per-entry-point instruction-count snapshot.
//!
//! Run with `UPDATE_GAS_SNAPSHOT=1 cargo test -p conduit-integration-tests --test gas_snapshot`
//! to regenerate `.gas-snapshot.json`. CI runs the same test without the
//! update flag and fails if the committed snapshot diverges, making cost
//! regressions visible in review.

use drip_factory::{DripFactory, DripFactoryClient};
use drip_governor::{DripGovernor, DripGovernorClient};
use soroban_sdk::{
    testutils::{Address as _, Ledger, LedgerInfo},
    Address, BytesN, Env,
};
use std::collections::BTreeMap;

#[derive(Debug, serde::Serialize, serde::Deserialize)]
struct Snapshot {
    /// Human-readable comment explaining how the snapshot is produced.
    comment: String,
    /// Measured CPU instruction counts per entry point.
    instructions: BTreeMap<String, u64>,
}

fn base_env() -> Env {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().set(LedgerInfo {
        timestamp: 1_000_000,
        protocol_version: 21,
        sequence_number: 1,
        network_id: Default::default(),
        base_reserve: 10,
        min_temp_entry_ttl: 16,
        min_persistent_entry_ttl: 4096,
        max_entry_ttl: 6_312_000,
    });
    env
}

fn deploy_factory(env: &Env) -> DripFactoryClient<'_> {
    let factory_id = env.register_contract(None, DripFactory);
    let governor_id = env.register_contract(None, DripGovernor);

    let authority = Address::generate(env);
    let fee_recipient = Address::generate(env);
    let governor_client = DripGovernorClient::new(env, &governor_id);
    governor_client.initialize(&authority, &fee_recipient, &factory_id);

    let client = DripFactoryClient::new(env, &factory_id);
    let dummy_hash = BytesN::from_array(env, &[1u8; 32]);
    client.initialize(&dummy_hash, &governor_id);
    client
}

#[test]
fn gas_snapshot_matches_committed_file() {
    let env = base_env();
    let factory = deploy_factory(&env);
    let sender = Address::generate(&env);
    let recip = Address::generate(&env);

    let mut instructions = BTreeMap::new();

    // Read-only entry points.
    env.budget().reset_default();
    factory.stream_count();
    instructions.insert("stream_count".into(), env.budget().cpu_instruction_cost());

    env.budget().reset_default();
    factory.protocol_fee_bps();
    instructions.insert(
        "protocol_fee_bps".into(),
        env.budget().cpu_instruction_cost(),
    );

    env.budget().reset_default();
    factory.streams_by_sender(&sender, &0, &10);
    instructions.insert(
        "streams_by_sender".into(),
        env.budget().cpu_instruction_cost(),
    );

    env.budget().reset_default();
    factory.streams_by_recipient(&recip, &0, &10);
    instructions.insert(
        "streams_by_recipient".into(),
        env.budget().cpu_instruction_cost(),
    );

    env.budget().reset_default();
    factory.aggregate();
    instructions.insert("aggregate".into(), env.budget().cpu_instruction_cost());

    // State-mutating entry points.
    env.budget().reset_default();
    factory.pause();
    instructions.insert("pause".into(), env.budget().cpu_instruction_cost());

    env.budget().reset_default();
    factory.unpause();
    instructions.insert("unpause".into(), env.budget().cpu_instruction_cost());

    let snapshot_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(".gas-snapshot.json");
    let update = std::env::var("UPDATE_GAS_SNAPSHOT").is_ok();

    if update {
        let snapshot = Snapshot {
            comment: "Auto-generated by tests/gas_snapshot.rs. Do not hand-edit.".into(),
            instructions,
        };
        std::fs::write(
            &snapshot_path,
            serde_json::to_string_pretty(&snapshot).unwrap(),
        )
        .expect("write snapshot");
    } else {
        let committed: Snapshot = serde_json::from_str(
            &std::fs::read_to_string(&snapshot_path)
                .expect("missing .gas-snapshot.json; run with UPDATE_GAS_SNAPSHOT=1"),
        )
        .expect("invalid snapshot JSON");

        let diff: BTreeMap<String, (u64, u64)> = instructions
            .iter()
            .filter_map(|(k, v)| {
                committed.instructions.get(k).and_then(|committed| {
                    if committed != v {
                        Some((k.clone(), (*committed, *v)))
                    } else {
                        None
                    }
                })
            })
            .collect();

        assert!(
            diff.is_empty(),
            "gas snapshot diff detected (committed -> current): {:?}",
            diff
        );
    }
}
